// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.github.qwchat.ceres.backend.dto;

public interface CommonResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.CommonResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
