// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.github.qwchat.ceres.backend.dto;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nickname = 1;</code>
   */
  java.lang.String getNickname();
  /**
   * <code>string nickname = 1;</code>
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();
}
