// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.github.qwchat.ceres.backend.dto;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.user.CommonResult result = 1;</code>
   */
  boolean hasResult();
  /**
   * <code>.user.CommonResult result = 1;</code>
   */
  com.github.qwchat.ceres.backend.dto.CommonResult getResult();
  /**
   * <code>.user.CommonResult result = 1;</code>
   */
  com.github.qwchat.ceres.backend.dto.CommonResultOrBuilder getResultOrBuilder();

  /**
   * <code>.user.UserInfo userInfo = 2;</code>
   */
  boolean hasUserInfo();
  /**
   * <code>.user.UserInfo userInfo = 2;</code>
   */
  com.github.qwchat.ceres.backend.dto.UserInfo getUserInfo();
  /**
   * <code>.user.UserInfo userInfo = 2;</code>
   */
  com.github.qwchat.ceres.backend.dto.UserInfoOrBuilder getUserInfoOrBuilder();
}
