// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.github.qwchat.ceres.backend.dto;

/**
 * Protobuf type {@code user.LoginResponse}
 */
public  final class LoginResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:user.LoginResponse)
    LoginResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LoginResponse.newBuilder() to construct.
  private LoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LoginResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LoginResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.github.qwchat.ceres.backend.dto.CommonResult.Builder subBuilder = null;
            if (result_ != null) {
              subBuilder = result_.toBuilder();
            }
            result_ = input.readMessage(com.github.qwchat.ceres.backend.dto.CommonResult.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(result_);
              result_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.github.qwchat.ceres.backend.dto.UserInfo.Builder subBuilder = null;
            if (userInfo_ != null) {
              subBuilder = userInfo_.toBuilder();
            }
            userInfo_ = input.readMessage(com.github.qwchat.ceres.backend.dto.UserInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(userInfo_);
              userInfo_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.qwchat.ceres.backend.dto.OuterUser.internal_static_user_LoginResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.qwchat.ceres.backend.dto.OuterUser.internal_static_user_LoginResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.qwchat.ceres.backend.dto.LoginResponse.class, com.github.qwchat.ceres.backend.dto.LoginResponse.Builder.class);
  }

  public static final int RESULT_FIELD_NUMBER = 1;
  private com.github.qwchat.ceres.backend.dto.CommonResult result_;
  /**
   * <code>.user.CommonResult result = 1;</code>
   */
  public boolean hasResult() {
    return result_ != null;
  }
  /**
   * <code>.user.CommonResult result = 1;</code>
   */
  public com.github.qwchat.ceres.backend.dto.CommonResult getResult() {
    return result_ == null ? com.github.qwchat.ceres.backend.dto.CommonResult.getDefaultInstance() : result_;
  }
  /**
   * <code>.user.CommonResult result = 1;</code>
   */
  public com.github.qwchat.ceres.backend.dto.CommonResultOrBuilder getResultOrBuilder() {
    return getResult();
  }

  public static final int USERINFO_FIELD_NUMBER = 2;
  private com.github.qwchat.ceres.backend.dto.UserInfo userInfo_;
  /**
   * <code>.user.UserInfo userInfo = 2;</code>
   */
  public boolean hasUserInfo() {
    return userInfo_ != null;
  }
  /**
   * <code>.user.UserInfo userInfo = 2;</code>
   */
  public com.github.qwchat.ceres.backend.dto.UserInfo getUserInfo() {
    return userInfo_ == null ? com.github.qwchat.ceres.backend.dto.UserInfo.getDefaultInstance() : userInfo_;
  }
  /**
   * <code>.user.UserInfo userInfo = 2;</code>
   */
  public com.github.qwchat.ceres.backend.dto.UserInfoOrBuilder getUserInfoOrBuilder() {
    return getUserInfo();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (result_ != null) {
      output.writeMessage(1, getResult());
    }
    if (userInfo_ != null) {
      output.writeMessage(2, getUserInfo());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (result_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getResult());
    }
    if (userInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUserInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.qwchat.ceres.backend.dto.LoginResponse)) {
      return super.equals(obj);
    }
    com.github.qwchat.ceres.backend.dto.LoginResponse other = (com.github.qwchat.ceres.backend.dto.LoginResponse) obj;

    boolean result = true;
    result = result && (hasResult() == other.hasResult());
    if (hasResult()) {
      result = result && getResult()
          .equals(other.getResult());
    }
    result = result && (hasUserInfo() == other.hasUserInfo());
    if (hasUserInfo()) {
      result = result && getUserInfo()
          .equals(other.getUserInfo());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasResult()) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
    }
    if (hasUserInfo()) {
      hash = (37 * hash) + USERINFO_FIELD_NUMBER;
      hash = (53 * hash) + getUserInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.qwchat.ceres.backend.dto.LoginResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.qwchat.ceres.backend.dto.LoginResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.qwchat.ceres.backend.dto.LoginResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.qwchat.ceres.backend.dto.LoginResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.qwchat.ceres.backend.dto.LoginResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.qwchat.ceres.backend.dto.LoginResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.qwchat.ceres.backend.dto.LoginResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.qwchat.ceres.backend.dto.LoginResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.qwchat.ceres.backend.dto.LoginResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.qwchat.ceres.backend.dto.LoginResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.qwchat.ceres.backend.dto.LoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.qwchat.ceres.backend.dto.LoginResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.qwchat.ceres.backend.dto.LoginResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code user.LoginResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:user.LoginResponse)
      com.github.qwchat.ceres.backend.dto.LoginResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.qwchat.ceres.backend.dto.OuterUser.internal_static_user_LoginResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.qwchat.ceres.backend.dto.OuterUser.internal_static_user_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.qwchat.ceres.backend.dto.LoginResponse.class, com.github.qwchat.ceres.backend.dto.LoginResponse.Builder.class);
    }

    // Construct using com.github.qwchat.ceres.backend.dto.LoginResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (resultBuilder_ == null) {
        result_ = null;
      } else {
        result_ = null;
        resultBuilder_ = null;
      }
      if (userInfoBuilder_ == null) {
        userInfo_ = null;
      } else {
        userInfo_ = null;
        userInfoBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.qwchat.ceres.backend.dto.OuterUser.internal_static_user_LoginResponse_descriptor;
    }

    public com.github.qwchat.ceres.backend.dto.LoginResponse getDefaultInstanceForType() {
      return com.github.qwchat.ceres.backend.dto.LoginResponse.getDefaultInstance();
    }

    public com.github.qwchat.ceres.backend.dto.LoginResponse build() {
      com.github.qwchat.ceres.backend.dto.LoginResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.github.qwchat.ceres.backend.dto.LoginResponse buildPartial() {
      com.github.qwchat.ceres.backend.dto.LoginResponse result = new com.github.qwchat.ceres.backend.dto.LoginResponse(this);
      if (resultBuilder_ == null) {
        result.result_ = result_;
      } else {
        result.result_ = resultBuilder_.build();
      }
      if (userInfoBuilder_ == null) {
        result.userInfo_ = userInfo_;
      } else {
        result.userInfo_ = userInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.qwchat.ceres.backend.dto.LoginResponse) {
        return mergeFrom((com.github.qwchat.ceres.backend.dto.LoginResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.qwchat.ceres.backend.dto.LoginResponse other) {
      if (other == com.github.qwchat.ceres.backend.dto.LoginResponse.getDefaultInstance()) return this;
      if (other.hasResult()) {
        mergeResult(other.getResult());
      }
      if (other.hasUserInfo()) {
        mergeUserInfo(other.getUserInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.qwchat.ceres.backend.dto.LoginResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.qwchat.ceres.backend.dto.LoginResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.github.qwchat.ceres.backend.dto.CommonResult result_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.qwchat.ceres.backend.dto.CommonResult, com.github.qwchat.ceres.backend.dto.CommonResult.Builder, com.github.qwchat.ceres.backend.dto.CommonResultOrBuilder> resultBuilder_;
    /**
     * <code>.user.CommonResult result = 1;</code>
     */
    public boolean hasResult() {
      return resultBuilder_ != null || result_ != null;
    }
    /**
     * <code>.user.CommonResult result = 1;</code>
     */
    public com.github.qwchat.ceres.backend.dto.CommonResult getResult() {
      if (resultBuilder_ == null) {
        return result_ == null ? com.github.qwchat.ceres.backend.dto.CommonResult.getDefaultInstance() : result_;
      } else {
        return resultBuilder_.getMessage();
      }
    }
    /**
     * <code>.user.CommonResult result = 1;</code>
     */
    public Builder setResult(com.github.qwchat.ceres.backend.dto.CommonResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        resultBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.user.CommonResult result = 1;</code>
     */
    public Builder setResult(
        com.github.qwchat.ceres.backend.dto.CommonResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        resultBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.user.CommonResult result = 1;</code>
     */
    public Builder mergeResult(com.github.qwchat.ceres.backend.dto.CommonResult value) {
      if (resultBuilder_ == null) {
        if (result_ != null) {
          result_ =
            com.github.qwchat.ceres.backend.dto.CommonResult.newBuilder(result_).mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        resultBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.user.CommonResult result = 1;</code>
     */
    public Builder clearResult() {
      if (resultBuilder_ == null) {
        result_ = null;
        onChanged();
      } else {
        result_ = null;
        resultBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.user.CommonResult result = 1;</code>
     */
    public com.github.qwchat.ceres.backend.dto.CommonResult.Builder getResultBuilder() {
      
      onChanged();
      return getResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.user.CommonResult result = 1;</code>
     */
    public com.github.qwchat.ceres.backend.dto.CommonResultOrBuilder getResultOrBuilder() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilder();
      } else {
        return result_ == null ?
            com.github.qwchat.ceres.backend.dto.CommonResult.getDefaultInstance() : result_;
      }
    }
    /**
     * <code>.user.CommonResult result = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.qwchat.ceres.backend.dto.CommonResult, com.github.qwchat.ceres.backend.dto.CommonResult.Builder, com.github.qwchat.ceres.backend.dto.CommonResultOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.qwchat.ceres.backend.dto.CommonResult, com.github.qwchat.ceres.backend.dto.CommonResult.Builder, com.github.qwchat.ceres.backend.dto.CommonResultOrBuilder>(
                getResult(),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }

    private com.github.qwchat.ceres.backend.dto.UserInfo userInfo_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.qwchat.ceres.backend.dto.UserInfo, com.github.qwchat.ceres.backend.dto.UserInfo.Builder, com.github.qwchat.ceres.backend.dto.UserInfoOrBuilder> userInfoBuilder_;
    /**
     * <code>.user.UserInfo userInfo = 2;</code>
     */
    public boolean hasUserInfo() {
      return userInfoBuilder_ != null || userInfo_ != null;
    }
    /**
     * <code>.user.UserInfo userInfo = 2;</code>
     */
    public com.github.qwchat.ceres.backend.dto.UserInfo getUserInfo() {
      if (userInfoBuilder_ == null) {
        return userInfo_ == null ? com.github.qwchat.ceres.backend.dto.UserInfo.getDefaultInstance() : userInfo_;
      } else {
        return userInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.user.UserInfo userInfo = 2;</code>
     */
    public Builder setUserInfo(com.github.qwchat.ceres.backend.dto.UserInfo value) {
      if (userInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        userInfo_ = value;
        onChanged();
      } else {
        userInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.user.UserInfo userInfo = 2;</code>
     */
    public Builder setUserInfo(
        com.github.qwchat.ceres.backend.dto.UserInfo.Builder builderForValue) {
      if (userInfoBuilder_ == null) {
        userInfo_ = builderForValue.build();
        onChanged();
      } else {
        userInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.user.UserInfo userInfo = 2;</code>
     */
    public Builder mergeUserInfo(com.github.qwchat.ceres.backend.dto.UserInfo value) {
      if (userInfoBuilder_ == null) {
        if (userInfo_ != null) {
          userInfo_ =
            com.github.qwchat.ceres.backend.dto.UserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
        } else {
          userInfo_ = value;
        }
        onChanged();
      } else {
        userInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.user.UserInfo userInfo = 2;</code>
     */
    public Builder clearUserInfo() {
      if (userInfoBuilder_ == null) {
        userInfo_ = null;
        onChanged();
      } else {
        userInfo_ = null;
        userInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.user.UserInfo userInfo = 2;</code>
     */
    public com.github.qwchat.ceres.backend.dto.UserInfo.Builder getUserInfoBuilder() {
      
      onChanged();
      return getUserInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.user.UserInfo userInfo = 2;</code>
     */
    public com.github.qwchat.ceres.backend.dto.UserInfoOrBuilder getUserInfoOrBuilder() {
      if (userInfoBuilder_ != null) {
        return userInfoBuilder_.getMessageOrBuilder();
      } else {
        return userInfo_ == null ?
            com.github.qwchat.ceres.backend.dto.UserInfo.getDefaultInstance() : userInfo_;
      }
    }
    /**
     * <code>.user.UserInfo userInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.qwchat.ceres.backend.dto.UserInfo, com.github.qwchat.ceres.backend.dto.UserInfo.Builder, com.github.qwchat.ceres.backend.dto.UserInfoOrBuilder> 
        getUserInfoFieldBuilder() {
      if (userInfoBuilder_ == null) {
        userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.qwchat.ceres.backend.dto.UserInfo, com.github.qwchat.ceres.backend.dto.UserInfo.Builder, com.github.qwchat.ceres.backend.dto.UserInfoOrBuilder>(
                getUserInfo(),
                getParentForChildren(),
                isClean());
        userInfo_ = null;
      }
      return userInfoBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:user.LoginResponse)
  }

  // @@protoc_insertion_point(class_scope:user.LoginResponse)
  private static final com.github.qwchat.ceres.backend.dto.LoginResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.qwchat.ceres.backend.dto.LoginResponse();
  }

  public static com.github.qwchat.ceres.backend.dto.LoginResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoginResponse>
      PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
    public LoginResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LoginResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LoginResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoginResponse> getParserForType() {
    return PARSER;
  }

  public com.github.qwchat.ceres.backend.dto.LoginResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

