// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.github.qwchat.ceres.backend.dto;

public final class OuterUser {
  private OuterUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_CommonResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_CommonResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_UserInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_UserInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_RegisterResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_user_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_user_LoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\004user\"/\n\014CommonResult\022\016\n\006st" +
      "atus\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\";\n\010UserInfo\022" +
      "\020\n\010nickname\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\022\016\n\006user" +
      "Id\030\003 \001(\t\"D\n\017RegisterRequest\022\020\n\010nickname\030" +
      "\001 \001(\t\022\020\n\010password\030\002 \001(\t\022\r\n\005email\030\003 \001(\t\"F" +
      "\n\020RegisterResponse\022\"\n\006result\030\001 \001(\0132\022.use" +
      "r.CommonResult\022\016\n\006userId\030\002 \001(\t\"2\n\014LoginR" +
      "equest\022\020\n\010nickname\030\001 \001(\t\022\020\n\010password\030\002 \001" +
      "(\t\"U\n\rLoginResponse\022\"\n\006result\030\001 \001(\0132\022.us" +
      "er.CommonResult\022 \n\010userInfo\030\002 \001(\0132\016.user" +
      ".UserInfo2s\n\004User\0229\n\010Register\022\025.user.Reg" +
      "isterRequest\032\026.user.RegisterResponse\0220\n\005" +
      "Login\022\022.user.LoginRequest\032\023.user.LoginRe" +
      "sponseB2\n#com.github.qwchat.ceres.backen" +
      "d.dtoB\tOuterUserP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_user_CommonResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_user_CommonResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_CommonResult_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_user_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_user_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_UserInfo_descriptor,
        new java.lang.String[] { "Nickname", "Email", "UserId", });
    internal_static_user_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_user_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_RegisterRequest_descriptor,
        new java.lang.String[] { "Nickname", "Password", "Email", });
    internal_static_user_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_user_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_RegisterResponse_descriptor,
        new java.lang.String[] { "Result", "UserId", });
    internal_static_user_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_user_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_LoginRequest_descriptor,
        new java.lang.String[] { "Nickname", "Password", });
    internal_static_user_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_user_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_user_LoginResponse_descriptor,
        new java.lang.String[] { "Result", "UserInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
