// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.github.qwchat.ceres.backend.dto;

public interface RegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.RegisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.user.CommonResult result = 1;</code>
   */
  boolean hasResult();
  /**
   * <code>.user.CommonResult result = 1;</code>
   */
  com.github.qwchat.ceres.backend.dto.CommonResult getResult();
  /**
   * <code>.user.CommonResult result = 1;</code>
   */
  com.github.qwchat.ceres.backend.dto.CommonResultOrBuilder getResultOrBuilder();

  /**
   * <code>string userId = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
