// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.github.qwchat.ceres.backend.dto;

public interface UserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.UserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nickname = 1;</code>
   */
  java.lang.String getNickname();
  /**
   * <code>string nickname = 1;</code>
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string userId = 3;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
